# Catppuccin Mocha Mauve

code_syntax_highlight = "catppuccin-mocha"

file_panel_border = "#6c7086"
sidebar_border = "#1e1e2e"
footer_border = "#6c7086"
file_panel_border_active = "#cba6f7"
sidebar_border_active = "#cba6f7"
footer_border_active = "#cba6f7"
modal_border_active = "#6c7086"
full_screen_bg = "#1e1e2e"
file_panel_bg = "#1e1e2e"
sidebar_bg = "#1e1e2e"
footer_bg = "#1e1e2e"
modal_bg = "#1e1e2e"
full_screen_fg = "#a6adc8"
file_panel_fg = "#a6adc8"
sidebar_fg = "#a6adc8"
footer_fg = "#a6adc8"
modal_fg = "#a6adc8"
cursor = "#f5e0dc"
correct = "#a6e3a1"
error = "#f38ba8"
hint = "#89dceb"
cancel = "#f5c2e7"
gradient_color = ["#89b4fa", "#cba6f7"]
directory_icon_color = "#89b4fa"
file_panel_top_directory_icon = "#a6e3a1"
file_panel_top_path = "#89b4fa"
file_panel_item_selected_fg = "#cba6f7"
file_panel_item_selected_bg = "#1e1e2e"
sidebar_title = "#89dceb"
sidebar_item_selected_fg = "#cba6f7"
sidebar_item_selected_bg = "#1e1e2e"
sidebar_divider = "#6c7086"
modal_cancel_fg = "#313244"
modal_cancel_bg = "#f5c2e7"
modal_confirm_fg = "#313244"
modal_confirm_bg = "#89dceb"
help_menu_hotkey = "#89dceb"
help_menu_title = "#f5c2e7"
